### PR TITLE
UFS-dev PR#220

### PR DESCRIPTION
**Pull request by grantfirl**
Analogous to https://github.com/NOAA-EMC/fv3atm/pull/861 and https://github.com/NOAA-EMC/fv3atm/pull/815

Note that fire coupling is not used/tested with the SCM, so changes from https://github.com/NOAA-EMC/fv3atm/pull/815 are mainly superficial.

No regression test changes.

### CODE REVIEW

**Review by dustinswales — COMMENTED** [review]
@grantfirl Not sure what happened with the CI? I'm rerunning them now via workflow dispatch.

**Comment by grantfirl** [comment]
> @grantfirl Not sure what happened with the CI? I'm rerunning them now via workflow dispatch.

@dustinswales We're all good now after fixes that I put in #529 .

**Review by dustinswales — APPROVED** [review]
Getting close. Woot Woot!

**Review by mkavulich — APPROVED** [review]
I am curious how a 1-d fire simulation would go 😆

**Pull request merged**
