### PR TITLE
Update SCM code for CCPP merges from 2021/07/09 through 2021/09/21

### PR DESCRIPTION
**Pull request by grantfirl**
This PR updates the SCM code to use the latest ccpp-physics main code as of 2021/09/21. Changes are analogous to those already merged into fv3atm.

Highlights:

- uses new tendencies
- uses new standard names
- contains code updates to work with all physics changes since early July

This work was performed by updating the SCM code to correspond to pull requests in ccpp-physics in chronological merge order. SCM regression tests were run and passed with identical output for code changes corresponding to ccpp-physics PRs #679, #695, #665, #681, #702, #715, #701, #525,714,716,717,718,721,722 (combined) and #705.

### CODE REVIEW

**Comment by grantfirl** [comment]
Replaces #269 and #264.

**Comment by grantfirl** [comment]
Requires changes in ccpp-physics: PR TBD

**Review by climbfuji — APPROVED** [review]
Looks good to me - I understand you need ccpp-physics PR https://github.com/NCAR/ccpp-physics/pull/731 merged first, which should happen today or tomorrow.

**Comment by grantfirl** [comment]
> Looks good to me - I understand you need ccpp-physics PR [NCAR/ccpp-physics#731](https://github.com/NCAR/ccpp-physics/pull/731) merged first, which should happen today or tomorrow.

OK, thanks. I see that #731 was pulled into #732. I don't think that the SCM needs any updates based on the other changes in #732, but after it is merged, I'll go ahead an re-run the SCM RTs to be safe and update the submodule pointers before merging this.

**Comment by grantfirl** [comment]
RTs were successful. Merging now...

**Pull request merged**
