### PR TITLE
Changes related to ccpp-physics PR#665 (and previous recent PRs)

### PR DESCRIPTION
**Pull request by grantfirl**
Note: requires followup PR for ccpp-physics for the SCM-specific scm_sfc_flux_spec.F90 scheme since changes were made to expected surface fluxes by PBL schemes.

### CODE REVIEW

**Review by climbfuji — APPROVED** [review]
This looks good to me, but just to clarify. Jongil's PR https://github.com/NCAR/ccpp-physics/pull/665 hasn't been merged yet. Does this mean that https://github.com/NCAR/ccpp-physics/pull/665 needs to be merged first, then you will create a follow-up SCM-only PR for ccpp-physics, and once that is merged the scm PR can be merged?

**Comment by grantfirl** [comment]
> This looks good to me, but just to clarify. Jongil's PR [NCAR/ccpp-physics#665](https://github.com/NCAR/ccpp-physics/pull/665) hasn't been merged yet. Does this mean that [NCAR/ccpp-physics#665](https://github.com/NCAR/ccpp-physics/pull/665) needs to be merged first, then you will create a follow-up SCM-only PR for ccpp-physics, and once that is merged the scm PR can be merged?

If Jongil is amenable to me pushing the changes to scm_spec_sfc_flux.[F90/meta] to his PR, then there won't need to be a followup. I can email him and ask. This SCM PR was created because some people within a DTC T&E project wanted to use Jongil's PR ASAP.

**Comment by grantfirl** [comment]
@climbfuji Since the SCM-only changes will not be merged with #665, I suppose this PR will follow the path that you laid out (followup ccpp-physics PR, update this PR, test, merge)

**Comment by grantfirl** [comment]
Closed in favor of #272

**Pull request closed without merging**
