### PR TITLE
unable to follow tutorial with singularity on hpc

### LINKED ISSUE #271: unable to follow tutorial with singularity on hpc
Hi, I have tried to follow the [tutorial](https://dtcenter.org/ccpp-scm-online-tutorial) using Singularity, but I couldn't get it to work as the tutorial shows. Could you please look into this and let me know if I am doing something wrong or if additional support is required for Singularity?

1. I made a directory and set the path, `export SCM_WORK='pwd' `
2. `singularity pull docker://dtcenter/ccpp-scm:v5.0.0-tutorial`
3. `export OUT_DIR=/path/to/output`
4. I tried a variety of Singularity calls, e.g. `singularity shell ccpp-scm_v5.0.0-tutorial.sif` and `singularity run ccpp-scm_v5.0.0-tutorial.sif` and `singularity exec --bind ${OUT_DIR}:/home ../ccpp-scm_v5.0.0-tutorial.sif` 
5. Once the Singularity image is activated (e.g. `Singularity>` prompt), I couldn't find the correct folders in the tutorial; that is, `cd $SCM_WORK/ccpp-scm/ccpp/suites` didn't work. The folder `ccpp-scm` didn't exist anywhere. I even tried `find . ccpp-scm` inside and outside the image in multiple directories to no avail. 

Do I need to pull the container in a specific way? (I don't think that was part of the tutorial.) Or do I need to bind the directories in different way than `--bind`. Generally, I think it would be much more helpful to have instructions for Singularity rather than Docker due to sudo rights associated with the latter. 

Thank you!

### PR DESCRIPTION
**Pull request by ngam**
Fixes #271

### CODE REVIEW

**Comment by ngam** [comment]
resolving this with a working example in Singularity, with detailed troubleshooting in case someone else runs into problems.

**Comment by climbfuji** [comment]
@ngam This PR has been sitting for a while, the biggest holdback being that none of us is using Singularity at the moment and thus no quick way to test it. If I set up Singularity on a Linux box, do you expect your instructions to work? If so, I may be able to set aside some time on the weekend and test your PR.

**Comment by ngam** [comment]
@climbfuji I think it should work, though it is a relatively crude solution. Part of the original problem was that there was a minor error in the tutorial instructions, and @grantfirl said he would relay that to the maintainers of the tutorial text. I can retest this soon as well, but generally speaking: the docker container you have is more than enough and if someone wants to use singularity, they can simply use singularity (see [here](https://sylabs.io/guides/2.6/user-guide/singularity_and_docker.html)) with the provided docker container (no need to actually redo the whole thing like I did here; I thought there was a deeper problem at the time, but I think it was simply the minor path error in the instructions).

So overall, I think this PR is moot --- sorry for the aggressive entry and annoyance (especially to @grantfirl). I still would like to make more use of this in the near future; I am currently stuck with other problems, but I hope to find time for this in early 2022.

**Comment by climbfuji** [comment]
> @climbfuji I think it should work, though it is a relatively crude solution. Part of the original problem was that there was a minor error in the tutorial instructions, and @grantfirl said he would relay that to the maintainers of the tutorial text. I can retest this soon as well, but generally speaking: the docker container you have is more than enough and if someone wants to use singularity, they can simply use singularity (see [here](https://sylabs.io/guides/2.6/user-guide/singularity_and_docker.html)) with the provided docker container (no need to actually redo the whole thing like I did here; I thought there was a deeper problem at the time, but I think it was simply the minor path error in the instructions).
> 
> So overall, I think this PR is moot --- sorry for the aggressive entry and annoyance (especially to @grantfirl). I still would like to make more use of this in the near future; I am currently stuck with other problems, but I hope to find time for this in early 2022.

Thanks for your quick reply. Have a great weekend!

**Pull request closed without merging**
