### PR TITLE
Github action version updates: Node.js 16 actions are deprecated

### PR DESCRIPTION
**Pull request by scrasmussen**
Updating Github action versions that the CI is warning are or will be deprecated. Updating `checkout` to v4, `setup-python` to v5, `cache` to v4, `upload-artifact` to v4, `setup-miniconda` to v3.

[Link to a run](https://github.com/NCAR/ccpp-scm/actions/runs/9199219368) with lots of example warning messages that `Node.js 16 actions are deprecated.`.

Tests Performed: the Github actions should run without any warnings.

Requires [CCPP-Physics PR#1072](https://github.com/NCAR/ccpp-physics/pull/1072)

### CODE REVIEW

**Comment by RobertPincus** [comment]
See #480

**Comment by grantfirl** [comment]
@scrasmussen Can you revert the ccpp/physics submodule update for now? We will bring in the GF fix that'll fix the nvfortran tests from a ufs/dev PR. I don't want to do it out of order.

**Comment by grantfirl** [comment]
I'll approve once the ccpp-physics submodule pointer change is reverted.

**Comment by scrasmussen** [comment]
> I'll approve once the ccpp-physics submodule pointer change is reverted.

Hi @grantfirl , sorry I had missed these comments, in a meeting now but will remove the ccpp/physics commit in an hour

**Comment by scrasmussen** [comment]
> > I'll approve once the ccpp-physics submodule pointer change is reverted.
> 
> Hi @grantfirl , sorry I had missed these comments, in a meeting now but will remove the ccpp/physics commit in an hour

Sorry was speed reading, looks like your commit fixed it? Will look closer after meeting

**Comment by grantfirl** [comment]
> > > I'll approve once the ccpp-physics submodule pointer change is reverted.
> > 
> > 
> > Hi @grantfirl , sorry I had missed these comments, in a meeting now but will remove the ccpp/physics commit in an hour
> 
> Sorry was speed reading, looks like your commit fixed it? Will look closer after meeting

@scrasmussen Ya, I just pulled in the latest main and pointed to the latest main of ccpp-physics rather than the PR that fixes the openACC bug because it is coming in separately.

**Comment by grantfirl** [comment]
Combining with https://github.com/NCAR/ccpp-scm/pull/486

**Pull request closed without merging**
