### PR TITLE
Add dependabot.yml to keep Github actions up to date

### PR DESCRIPTION
**Pull request by RobertPincus**
This file runs a bot daily to keep your Github actions versions up to date.

### CODE REVIEW

**Comment by dustinswales** [comment]
@RobertPincus Thanks for this. Cool stuff.
Just so I understand how this works, this script will open PRs into the target_branch, "main", if our action versions get out of date?

**Comment by RobertPincus** [comment]
Exactly right @dustinswales

**Comment by RobertPincus** [comment]
Maybe merge after #478

**Comment by grantfirl** [comment]
I'll approve after #478 is merged and this branch pulls in the newly merged main branch.

**Comment by grantfirl** [comment]
Combining with https://github.com/NCAR/ccpp-scm/pull/486

**Pull request closed without merging**
