### PR TITLE
UFS-dev PR#26

### PR DESCRIPTION
**Pull request by grantfirl**
analogous to https://github.com/NOAA-EMC/fv3atm/pull/606

Note that although these changes allow the SCM to compile and run through the field campaign cases, more work will need to be done in the input and UFS column simulator script to work with a lake point.

### CODE REVIEW

**Comment by grantfirl** [comment]
@mkavulich One more to review for ufs/dev PR#26 ...

**Review by mkavulich — APPROVED** [review]
@grantfirl Sorry about that, approved.

Random question if you get a chance: is there a reason the SCM maintains its own duplicate list of constants instead of using physcons.F90 from ccpp-physics? I've never noticed that's the case before this PR.

**Comment by grantfirl** [comment]
> @grantfirl Sorry about that, approved.
> 
> Random question if you get a chance: is there a reason the SCM maintains its own duplicate list of constants instead of using physcons.F90 from ccpp-physics? I've never noticed that's the case before this PR.

I think that we (Dom and others) that physcons.F90 doesn't belong in the CCPP since it is a host-specific file. For some reason, this hasn't been removed from ccpp-physics, but the SCM was coded as-if it doesn't exist.

**Comment by dustinswales** [comment]
> > @grantfirl Sorry about that, approved.
> > Random question if you get a chance: is there a reason the SCM maintains its own duplicate list of constants instead of using physcons.F90 from ccpp-physics? I've never noticed that's the case before this PR.
> 
> I think that we (Dom and others) that physcons.F90 doesn't belong in the CCPP since it is a host-specific file. For some reason, this hasn't been removed from ccpp-physics, but the SCM was coded as-if it doesn't exist.

I second that emotion.

**Pull request merged**
