### PR TITLE
Updates of ccpp-scm to work with ccpp-framework hash 47a5f65ae6b760b513d7babfbe66138a8f4a23bc and ccpp-physics hash eb28756036b280c2c1a741112045fefd5639c6a9

### PR DESCRIPTION
**Pull request by climbfuji**
Updates of ccpp-scm to work with ccpp-framework hash 47a5f65ae6b760b513d7babfbe66138a8f4a23bc and ccpp-physics hash eb28756036b280c2c1a741112045fefd5639c6a9.

Tested on macOS with GNU for all 25 permutations.

Changes in CCPP framework and physics:
- remove WRFv4 Noah LSM
- add debugging features for auto-generatedd CCPP caps
- semi-Lagrangian sedimentation of rain Thompson MP
- removal of optional attribute from CCPP framework and metadata
- updates to sfc_sice and removal of several interstitial variables w.r.t. fractional grids
- additional bugfixes and improvements

### CODE REVIEW

**Comment by grantfirl** [comment]
@climbfuji I'm RTing this now...

**Review by grantfirl — APPROVED** [review]
Regression tests passed with identical output and the changes looks fine to me.

**Comment by grantfirl** [comment]
@climbfuji @llpcarson This is ready to be merged, but I don't have permissions anymore to do so. Could one of you merge or add me back as repo owner? @climbfuji I read through the NOAA GitHub user document and the only thing that I see that I needed to do was turn on 2FA, which I did. Unless we want to turn this repo into part of the NOAAGov account, I think that we're OK.

**Comment by climbfuji** [comment]
@grantfirl you have been re-instantiated as admin for your repo

**Pull request merged**
