### PR TITLE
Add more wildcard characters to filenames and add soil color to LSM IC

### PR DESCRIPTION
**Pull request by bluefinweiwei**
1) Add wildcard characters * for various output filenames, e.g., gfs.t00z.atmf0000.nc, gfs.t00z.sfcf0000.nc, oro_C96.mx100.tile1.nc. 
2) Add soil color (a new soil property in Noah-MP) to get LSM IC set correctly, otherwise, forcing is not generated due to a crash.
- modified:   UFS_IC_generator.py
- modified:   extract_FV3GFS_column_ic.py

### CODE REVIEW

**Comment by dustinswales** [comment]
@bluefinweiwei These changes look fine to me, and the UFS-replay CI test passes, so good job!
@grantfirl What's the story with [extract_FV3GFS_column_ic.py](https://github.com/NCAR/ccpp-scm/pull/419/files#diff-e2a166c1402bd3d54f7bb988cc8fd89e4ed47221f0cfdd10b68f97b93a0b0e1f)? Is this a script that is still used?

**Comment by grantfirl** [comment]
> @bluefinweiwei These changes look fine to me, and the UFS-replay CI test passes, so good job! @grantfirl What's the story with [extract_FV3GFS_column_ic.py](https://github.com/NCAR/ccpp-scm/pull/419/files#diff-e2a166c1402bd3d54f7bb988cc8fd89e4ed47221f0cfdd10b68f97b93a0b0e1f)? Is this a script that is still used?

I don't think that this is being used anymore. I think that this was a precursor to UFS_IC_generator.py from Phil Pegion that I slightly modified. I think that we can probably safely remove it from the repo going forward.

**Comment by grantfirl** [comment]
@bluefinweiwei I'm combining these changes into #459 with others to streamline the open PRs, so I'm closing this. Thanks for the work!

**Comment by bluefinweiwei** [comment]
Sounds great, thanks!

**Pull request closed without merging**
