### PR TITLE
Add new conda environment to Cheyenne setup files

### PR DESCRIPTION
**Pull request by mkavulich**
This conda environment was created using the following commands, and was sufficient to run the online tutorial case:

```
conda create --prefix=/glade/p/ral/jntp/GMTB/CCPP_SCM/conda/ccpp-scm python=3.7
conda activate /glade/p/ral/jntp/GMTB/CCPP_SCM/conda/ccpp-scm/
conda install -c conda-forge xarray dask netCDF4 bottleneck matplotlib f90nml xesmf
conda install configobj
```

It has been tested successfully with the online tutorial case for Intel with bash shell, I have not tested other configurations yet.

### CODE REVIEW

**Comment by dustinswales** [comment]
@mkavulich Looks great. Thanks for creating this. We also need scipy, shapely, and pandas.

**Comment by mkavulich** [comment]
@dustinswales Added scipy. Shapely and pandas were already installed as prerequisites for other packages. I have attached the full .yml description of the conda environment:

[ccpp-scm-yml.txt](https://github.com/NCAR/ccpp-scm/files/8959192/ccpp-scm-yml.txt)
t

**Review by dustinswales — APPROVED** [review]
Looks great. Thanks!

**Comment by grantfirl** [comment]
Thanks @mkavulich. I'll test this environment. If there is something missing, it shouldn't require any changes to the repo, only adding something to the environment that we activate, so that is nice. I'm guessing that `module load conda/latest` calls the conda initialization script such that `conda activate` is available? I know that on Hera, we need the setup scripts to call the conda initialization script before trying `conda activate`.

**Pull request merged**
