### PR TITLE
implement timestep_init phases and catch up with master of ccpp-physics (2021/03/04)

### PR DESCRIPTION
**Pull request by grantfirl**
Replaces #223

- Implement the timestep_init/finalize phases in SCM source code
- update to ccpp-physics master as of 2021/03/04
- change build system so that ccpp_prebuild.py writes caps/cmake snippets to build directory rather than src directory (this now works with the default CMakeLists.txt in ccpp-physics)
- change the diagnostic bucket clearing to SCM code
-- change timing of diagnostic clearing (order of operations was wrong)
-- allow for diagnostic clearing every timestep
 - comment out reading in RUC LSM init variables since changes to ccpp-physics has rendered it obsolete (followup PR needed to read in RUC LSM init data)

### CODE REVIEW

**Comment by grantfirl** [comment]
Will likely need followup PR to accommodate recent changes in LSM initializations. The existing canned cases have been tested to work with this PR.

**Comment by grantfirl** [comment]
There are many whitespace changes in GFS_typedefs.F90/meta. This is on purpose to match changes in the FV3 versions of these files.

**Comment by grantfirl** [comment]
Associated with https://github.com/NCAR/ccpp-physics/pull/562, which has already been merged.

**Comment by grantfirl** [comment]
@dustinswales This catches the SCM up with ccpp-physics master, including recently merged RRTMGP changes.

**Review by climbfuji — APPROVED** [review]

**Pull request merged**
