### PR TITLE
transfer v5 release changes to master

### PR DESCRIPTION
**Pull request by grantfirl**
This should wait to be merged until ccpp-physics v5 release changes have been merged into master.

### CODE REVIEW

**Comment by climbfuji** [comment]
Which ccpp-physics v5 release changes are you referring to? I think there is very little that needs to be brought over. Essentially only the GNU 10 updates (use assumed sizes instead of specified dimensions).

**Comment by grantfirl** [comment]
> Which ccpp-physics v5 release changes are you referring to? I think there is very little that needs to be brought over. Essentially only the GNU 10 updates (use assumed sizes instead of specified dimensions).

Mainly the bugfixes that only went into the release branch and the removal of 'gmtb' from SCM-specific files.

**Comment by grantfirl** [comment]
Associated PR: https://github.com/NCAR/ccpp-physics/pull/626

**Comment by grantfirl** [comment]
This code was tested to build/compile/run on Hera/Intel, Cheyenne/GNU, Cheyenne/Intel with https://github.com/NCAR/ccpp-physics/pull/626 (also with https://github.com/NCAR/ccpp-physics/pull/613 for debug mode).

**Comment by llpcarson** [comment]
@grantfirl https://github.com/NCAR/ccpp-physics/pull/626 is merged.

**Comment by grantfirl** [comment]
This again compiles and runs on all supported platforms. Requires https://github.com/NCAR/ccpp-physics/pull/643 to compile.

**Comment by grantfirl** [comment]
After NCAR/ccpp-physics#643 was merged with NCAR/ccpp-physics#611 (and after some MORE updates to GFS_typedefs, etc. to work with the latest ccpp-physics master changes), this once again compiles runs on all supported platforms.

**Comment by grantfirl** [comment]
The code is producing seg faults on Cheyenne/GNU/release. If I can't figure it out, I might want to merge anyway and fix later just so this PR doesn't get further behind...

**Review by llpcarson — APPROVED** [review]
Will approve, with possible known issue for Gnu to be fixed in a later commit.

**Comment by grantfirl** [comment]
Thanks, I figured out the issue. See https://github.com/NCAR/ccpp-physics/pull/652. I'd still like to merge this, since it is not a SCM problem.

**Comment by grantfirl** [comment]
> The code is producing seg faults on Cheyenne/GNU/release. If I can't figure it out, I might want to merge anyway and fix later just so this PR doesn't get further behind...

See https://github.com/NCAR/ccpp-physics/issues/651 and https://github.com/NCAR/ccpp-physics/pull/652.

**Pull request merged**
