### PR TITLE
UFS-dev PR#42

### PR DESCRIPTION
**Pull request by grantfirl**
Changes to GFS_typedefs to work with [ufs/dev #42](https://github.com/NCAR/ccpp-physics/pull/1007). The changes are analogous to https://github.com/NCAR/fv3atm/pull/89

### CODE REVIEW

**Comment by grantfirl** [comment]
Contains changes from #373 and depends on it being merged first. Also depends on https://github.com/NCAR/ccpp-physics/pull/1007.

**Review by dustinswales — APPROVED** [review]

**Comment by dustinswales** [comment]
@grantfirl I think this is good to go?
It's a bit troublesome that we are seeing lots of BL changes in the UWM, but not in here. https://github.com/NCAR/ufs-weather-model/pull/92?

**Comment by grantfirl** [comment]
> @grantfirl I think this is good to go? It's a bit troublesome that we are seeing lots of BL changes in the UWM, but not in here. [NCAR/ufs-weather-model#92](https://github.com/NCAR/ufs-weather-model/pull/92)?

Ya, this probably needs to be verified. I'm also not sure that the failures in UWM are all expected since it wasn't explicitly mentioned in the UFS fork which RTs should fail. I've asked Sam for some clues, but haven't heard back. I'll look at this a bit more later this afternoon.

**Comment by grantfirl** [comment]
@dustinswales Do you know when the last time ftp://ftp.rap.ucar.edu/pub/ccpp-scm/rt-baselines-Debug.zip was updated?

**Comment by grantfirl** [comment]
Should https://github.com/NCAR/ccpp-scm/blob/main/test/cmp_rt2bl.py be using nccmp rather than cmp?

**Comment by dustinswales** [comment]
> @dustinswales Do you know when the last time ftp://ftp.rap.ucar.edu/pub/ccpp-scm/rt-baselines-Debug.zip was updated?

@grantfirl I updated them the last time they changed, which was a few weeks ago.

**Pull request merged**
