### PR TITLE
UFS/dev PR#54

### PR DESCRIPTION
**Pull request by grantfirl**
Updates to GFS_typedefs and ccpp_prebuild_config.py to work with https://github.com/NCAR/ccpp-physics/pull/1008. This has changes analogous to https://github.com/NCAR/fv3atm/pull/90.

Note that additional changes for input might be needed to use the smoke/dust code.

### CODE REVIEW

**Review by dustinswales — APPROVED** [review]

**Comment by grantfirl** [comment]
@dustinswales I have no idea why GitHub is complaining about a conflict in ccpp/physics. It is pointing to the right commit of ccpp/physics.

**Comment by grantfirl** [comment]
I also don't know where the CI stuff went. I'm not seeing it here.

**Comment by grantfirl** [comment]
Oh, I think I know what I did. Hold on.

**Comment by grantfirl** [comment]
@dustinswales BLs have changed with this PR. Could you update the FTP site or give me instructions for doing that (although I probably lack permissions)?

**Comment by dustinswales** [comment]
@grantfirl I'll update the FTP site with new baselines, and then rerun the tests. (I think this is a good opportunity to bring @mkavulich in this process.)

**Comment by grantfirl** [comment]
> @grantfirl I'll update the FTP site with new baselines, and then rerun the tests. (I think this is a good opportunity to bring @mkavulich in this process.)

Ya, absolutely, since @mkavulich should have all permissions already and he can help when you're out.

**Pull request merged**
